name: CI SPACE SHOOTER

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake \
          libasound2-dev libx11-dev libxrandr-dev libxi-dev \
          libgl1-mesa-dev libglu1-mesa-dev xorg-dev

    - name: Cache raylib 5.5
      id: cache-raylib
      uses: actions/cache@v4
      with:
        path: ./raylib-5.5
        key: ${{ runner.os }}-raylib-5.5

    - name: Build and Install raylib 5.5
      if: steps.cache-raylib.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 --branch 5.5 https://github.com/raysan5/raylib.git raylib-5.5
        cd raylib-5.5/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    - name: Re-install raylib if cached
      if: steps.cache-raylib.outputs.cache-hit == 'true'
      run: |
        cd raylib-5.5/src
        sudo make install

    - name: Build Project
      run: make
